### ISSUE TITLE
Add mutations for associations?

### ISSUE THREAD

**Issue by tmeasday** [tmeasday/create-graphql-server#1]
It seems like it would be useful to generate something like

```graphql
Mutation {
  createUserFollower(userId: ID!, follower: UserInput!): User
  addToUserFollowersById(userId: ID!, followerId: ID!): User
  setUserFollowers(userId: ID!, followerIds: [ID!]!): User
  removeFromUserFollowersById(userId: ID!, followerId: ID!): Boolean
}
```

1. Does it make sense to generate all of these methods?
2. Are there any others we should add?
3. How to deal with pluralization? (We were leaning towards not doing Rails-style auto-pluralization but it becomes real hard to give non-crappy names without singularizing `followers`)

**Comment by tmeasday** [comment]
It's also not hard to see that a lot of the time these *won't* make sense. Is it worth generating bogus ones that the user needs to remove in order to get the useful ones?

**Comment by tmeasday** [comment]
Alternatively, we could add a directive to ask for them.

**Comment by stubailo** [comment]
Hmm, Rails doesn't do these, right? I guess I wish there was a way to have a command to add them one-by-one when necessary. Perhaps if we enforce really strict code style we can have the generator be capable of adding a field?

**Comment by tmeasday** [comment]
> Hmm, Rails doesn't do these, right? 

Well.. it depends what you mean. Rails makes it super easy to modify the association with like `followers.create(...)`, `followers << follower`, `follower_ids << id`, etc.

It doesn't add any actions for the above however, which I guess would be the closest analogy to a mutation.

I don't think it makes sense for us to generate model methods that aren't used from the resolver layer; however I guess the generated API would be more useful with the above (you could build a bit of API w/o touching the generated code).

Lets see how we go without them for now maybe.

> Perhaps if we enforce really strict code style we can have the generator be capable of adding a field?

That sounds really tricky and probably counter-productive I'd say

**Comment by tmeasday** [comment]
Maybe a more railsy thing to do is to extend the input type:

```graphql
input UserInput {
  username String!
  bio String

  followerIds [ID!]
  addFollowerId ID!
  removeFollowerId ID!
}
```

Or even
```graphql
input AssociatedArrayInput {
  setIds [ID!]
  addId ID!
  removeId ID!
}

input UserInput {
  username String!
  bio String

  followers AssociatedArrayInput
}
```

**Comment by tmeasday** [comment]
We discussed this and decided not to head in this direction, as this is not what we'd write ourselves if we were writing a schema.
