### ISSUE TITLE
Relation directives

### ISSUE THREAD

**Issue by tmeasday** [tmeasday/create-graphql-server#2]
It might be more flexible to instead of:

```graphql
  tweets: [Tweet!] @hasMany(as: "author")
```

write

```graphql
  tweets: [Tweet!] @as(key: "author") @paginated
```

Also we should potentially paginated all array fields by default?

**Comment by stubailo** [comment]
I feel like it's not a good idea to split stuff across multiple directives - why not just `@hasMany(as: "author", paginated: true)` or similar?

**Comment by tmeasday** [comment]
Make sense.
