### ISSUE TITLE
Add basic Auth w/ passport and JWT

### ISSUE THREAD

**Issue by tmeasday** [tmeasday/create-graphql-server#21]

**Comment by dweldon** [comment]
I'm excited to see that implemented. After reading [this](http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/) I'm a little scared of JWT. Is the primary reason for CORS?

**Comment by tmeasday** [comment]
@dweldon, yeah I read this and was put off at first but reading around a little more (I don't have the links, sorry!) I convinced myself it was OK. As that article says, there are 2 axes to compare JWT to cookies+ss-session:

1. cookies vs local-storage:
  - If you read around I think you'll agree that although people use very strong language, it is by no means clear that cookies are more secure than local storage. There's an objection about needing JS, but... well.. ;)

2. JWT vs server-stored session:
  - We aren't storing a session in the JWT token, just a user id, so most of the arguments against JWT "stateless" sessions don't apply.
  - Even if we were, I don't buy the arguments stated particular much. You *can* invalidate individual tokens (sure it requires server state, but so does every other solution stated). You can build a expiry into the token to deal with the staleness problem[1], and "implementations aren't battletested" is a bit of a silly chicken and egg argument, IMO.

Anyway, LMK if you disagree :)


[1] We should probably be doing this already, PRs encouraged! :)
