### ISSUE TITLE
create-graphql-server add-type naively appends to index files

### ISSUE THREAD

**Issue by d3r1v3d** [tmeasday/create-graphql-server#34]
Version `0.5.3` will append model, resolver, and schema hooks to their respective index files for every type added through a call to `create-graphql-server add-type ...`. This ends up appending the same set of lines over and over to the bottom of each of these files -- triggering a slew of linter errors.

Understandable, since it's generated code and difficult to detect whether these imports already exist. However, I'd recommend either looking for identical lines already present in a file (which is difficult anyways since users might have completely reformatted everything about the initial import) or else generate a notice message whenever the tool runs to indicate these changes are being made.

Just a small nit, though. This tool is awesome!

**Comment by tmeasday** [comment]
Hey @d3r1v3d! Thanks for your kind words. 

Actually the excellent @tobkle already fixed this, I think I just neglected to release it (seehttps://github.com/tmeasday/create-graphql-server/blob/master/CHANGELOG.md).

I'll release it now. Let me know how it goes.
