### ISSUE TITLE
add-type cannot read a file

### ISSUE THREAD

**Issue by mayacode** [tmeasday/create-graphql-server#42]
I have node 7.10, freshly installed create-graphql-server, initialized new project and ran it. Here everything works.

But the moment I try to create new type, it is not working. Running command: `$ create-graphql-server add-type ./User.graphql` gave me an output:
```
CREATE-GRAPHQL-SERVER

Running add-type
Error: Cannot read file ./User.graphql
```
I tried to run it with sudo (in the case of some strange permission related things) but still the same problem. I would appreciate any hints how to make it work

**Comment by tmeasday** [comment]
Does this file `./User.graphql` exist relative to where you are running the command?

**Comment by mayacode** [comment]
Your comment plus reading readme again (believe me I read it before few times) finally gave me a hint what I'm doing wrong. Closing issue. Thanks

**Comment by tmeasday** [comment]
Glad you figured it out
