### ISSUE TITLE
Reuse model instances?

### ISSUE THREAD

**Issue by lorensr** [tmeasday/create-graphql-server#52]
I noticed this because one of my models starts polling on creation. 

We're not giving any request info to `addModelsToContext()`, so is there a point to creating new model instances for every request? If not, we could just do it once:

```js
+  const context = addModelsToContext({ db, pubsub })
+
   const app = express().use('*', cors())
   app.use(bodyParser.urlencoded({ extended: true }))
   app.use(bodyParser.json())
 
   app.use((req, res, next) => {
-    req.context = addModelsToContext({ db, pubsub })
+    req.context = context
     next()
```

**Comment by tmeasday** [comment]
Hi @lorensr. The primary reason to create a new model for every request is for data-loader's sake -- it [expects to be reset per-request](https://github.com/facebook/dataloader#caching-per-request).

Also, we set the `{user}` on the context object per-request, and you may want to access it in your models. I'm still not sure if that's a good idea TBH.

**Comment by lorensr** [comment]
Oh right! Thanks 😊
